CovidApts/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.NodeServices;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using CovidApts.Data;
using CovidApts.Models;
using CovidApts.Services;
using CovidApts.ViewModels;

namespace CovidApts.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly CovidAptsDbContext _context;
        private readonly IHostingEnvironment he;

        public CompaniesController(CovidAptsDbContext context, IHostingEnvironment e)
        {
            _context = context;
            he = e;
        }

        // POST: Get Companies parameters from the user and search in server
        //       it shows the Companies details and also user name, appartment password
        public async Task<IActionResult> ShowMalfExtraDetails(DateTime createDate, Status status,
                                                              string address, string userName)
        {
            if ((createDate == null) && (String.IsNullOrEmpty(status.ToString())) &&
                  String.IsNullOrEmpty(address) && String.IsNullOrEmpty(userName))
            {
                return View(await _context.Company.ToListAsync());
            }

            return (await SearchMalfExtraDetails(createDate, status, address, userName));
        }

        private async Task<IActionResult> SearchMalfExtraDetails(DateTime createDate, Status status,
                                                              string address, string userName)
        {
            Status enumStatus = (Status)status;

            if (address == null)
                address = "";

            var q = from Company in _context.Company
                    join apartments in _context.Apartment on Company.CurrentApartment equals apartments
                    where Company.CreationDate >= createDate &&
                          Company.Status.Equals(enumStatus) &&
                          apartments.Address.Contains(address)
                    select new ExtraDetailsCompaniesVM()
                    {
                        Title = Company.Title,
                        Status = Company.Status.ToString(),
                        Content = Company.Content,
                        CreationDate = Company.CreationDate,
                        ModifiedDate = Company.ModifiedDate,
                        AppartmentAddress = apartments.Address,
                    };

             return View(await q.ToListAsync());
    }

        // GET: Companies
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Index(String searchString)
        {
            var databaseContext = _context.Company.Include(p => p.CurrentApartment);

            if (String.IsNullOrEmpty(searchString))
            {
                return View(await databaseContext.ToListAsync());
            }

            return View(await databaseContext.Where(m => m.Content.Contains(searchString)).ToListAsync());
        }

        // GET: Companies/Details/5
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var Company = await _context.Company
                .FirstOrDefaultAsync(m => m.CompanyId == id);
            if (Company == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(Company);
        }

        // GET: Companies/Create
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Create()
        {
            var apartments = from apt in _context.Apartment.Include(s => s.Companies)
                             select new { Value = apt.ApartmentId, Text = apt.Address };

            var users = from usr in _context.User.Include(s => s.Companies)
                        select new { Value = usr.Id, Text = usr.Email };

            var statuses = from Status stat in Enum.GetValues(typeof(Status))
                           select new { Value = (int)stat, Text = stat.ToString() };

            ViewData["all_appartments"] = new SelectList(await apartments.ToListAsync(), "Value", "Text");
            ViewData["all_users"] = new SelectList(await users.ToListAsync(), "Value", "Text");
            ViewData["statuses"] = new SelectList(statuses, "Value", "Text");

            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Create([Bind("CurrentApartment")]int CurrentApartment, [Bind("CompanyId,Status,Title,Content,Resources,CurrentApartmentId")] Company Company, IFormFile mFiles)
        {            
            if (ModelState.IsValid)
            {
                // Creating the query of the apartment
                var queryApt = from apt in _context.Apartment
                               where apt.ApartmentId == CurrentApartment
                               select apt;

                // If the id of the apartment/user does not exist in DB
                if (!queryApt.Any() || !queryApt.Any())
                {
                    return View(Company);
                }

                // Adding the apartment to the Company to save
                var curApartment = queryApt.First();
                Company.CurrentApartment = curApartment;
                
                // Adding the creation date and modification date
                Company.CreationDate = DateTime.Now;
                Company.ModifiedDate = DateTime.Now;

                // Uploading photo describing the Company
                SavePhoto(Company, mFiles);

                _context.Add(Company);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(Company);
        }

        private void SavePhoto(Company Company, IFormFile mFiles)
        {
            // Sanity check apartment cant be null
            if (Company == null)
            {
                return;
            }

            // If there is no defined photo, set the default photo
            if (mFiles == null)
            {
                Company.Resources = "/images/Companies/default_Company_photo.jpg";
                return;
            }

            var fileName = Path.Combine(he.WebRootPath + "/images/Companies", Path.GetFileName(mFiles.FileName));
            Company.Resources = "/images/Companies/" + mFiles.FileName;

            // If the file does not exist already creating it
            if (!System.IO.File.Exists(fileName))
            {
                mFiles.CopyTo(new FileStream(fileName, FileMode.Create));
            }
        }

        // GET: Companies/Edit/5
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var Company = await _context.Company.FindAsync(id);
            if (Company == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            // Adding all the statuses to the viewData
            var statuses = from Status stat in Enum.GetValues(typeof(Status))
                select new { Value = (int)stat, Text = stat.ToString() };
            ViewData["statuses"] = new SelectList(statuses, "Value", "Text");

            return View(Company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Edit(string id, [Bind("CompanyId,Status,Title,Content,Resources")] Company Company, IFormFile files)
        {
            if (id != Company.CompanyId)
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    SavePhoto(Company, files);
                }

                if (!CompanyExists(Company.CompanyId))
                    return RedirectToAction("NotFoundPage");

                // Getting the Company from db
                var CompanyToSave = _context.Company.First(mal => mal.CompanyId == id);

                // Setting the new values
                CompanyToSave.ModifiedDate = DateTime.Now;
                CompanyToSave.Status = Company.Status;
                CompanyToSave.Title = Company.Title;
                CompanyToSave.Content = Company.Content;
                CompanyToSave.Resources = Company.Resources;

                // Updating the new Company
                _context.Update(CompanyToSave);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(Company);
        }

        // GET: Companies/Delete/5
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Delete(string id)

CovidApts/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CovidApts.Data;
using Microsoft.AspNetCore.Authorization;
using CovidApts.Models;
using Microsoft.AspNetCore.Identity;

namespace CovidApts.Controllers
{
    public class UsersController : Controller
    {
        private readonly CovidAptsDbContext _context;
        private readonly UserManager<User> _userManager;

        public UsersController(CovidAptsDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private async Task<IActionResult> SearchUserDetails(string Name, string Email, string Address)
        {
            //_context.User.Where(m => m.Email.Contains(Email) && m.FullName.Contains(Name) && m.Address.Contains(Address));
            var q = from users in _context.User
                    where (Name == null || users.FullName.ToLower().Contains(Name.ToLower())) &&
                          (Email == null || users.Email.ToLower().Contains(Email.ToLower())) &&
                          (Address == null || users.Address.ToLower().Contains(Address.ToLower()))
                    select users;

            return View(await q.ToListAsync());
        }

        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Index(string Name, string Email, string Address)
        {
            if (String.IsNullOrEmpty(Name) && String.IsNullOrEmpty(Email) && String.IsNullOrEmpty(Address))
            {
                return View(await _context.User.ToListAsync());
            }

            return (await SearchUserDetails(Name, Email, Address));
        }

        public async Task<IActionResult> Details(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id.ToString());

            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(user);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }
            if (_userManager.GetUserId(HttpContext.User).Equals(id))
            {
                return Redirect("/Identity/Account/Manage");
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(String id, [Bind("Id,FullName,Email,PhoneNumber,Address")] User user)
        {
            if (!id.Equals(user.Id))
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    User dbUser = (User)_context.Users.First(u => u.Id == id);
                    dbUser.PhoneNumber = user.PhoneNumber;
                    dbUser.FullName = user.FullName;
                    dbUser.Address = user.Address;
                    _context.Update(dbUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return RedirectToAction("NotFoundPage");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        private bool UserExists(String id)
        {
            return _context.User.Any(e => e.Id == id);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(String id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult NotFoundPage()
        {
            return View();
        }
    }

}

CovidApts/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CovidApts</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/main.css" />
        <link rel="stylesheet" href="~/css/Navbar-Dropdown.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="~/css/layout.css" />
        <style type="text/css">
            
        </style>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div id="dialog" title="Welcome!" class="dialog-message">
        <p>This site created by Idan Aharoni, Omri Siniver and Yuval Sages. Please register first!</p>
    </div>

    <nav id="nav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Apartments" asp-action="Index" class="navbar-brand" style="color:white">CovidApts</a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="myDropdown_navbar">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Users" asp-action="Index" style="color: white">Users</a></li>
                        <li><a asp-area="" asp-controller="Companies" asp-action="Index" style="color:white">Companies</a></li>
                        <li><a asp-area="" asp-controller="Statistics" asp-action="Index" style="color:white">Statistics</a></li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="Companies" asp-action="ShowMalfExtraDetails" style="color:white">Manager</a></li>
                        }
                        <li><a asp-area="" asp-controller="Apartments" asp-action="About" style="color:white">About</a></li>
                        <li><a asp-area="" asp-controller="Apartments" asp-action="Contact" style="color:white">Contact</a></li>
                        <li>
                            <a id="help" style="color:white">?</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name">Covid Apts</span>
                        <span class="skills">Your platform to find and host your apartment as shared workspace</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="width:100%">

            <aside style="width:40%">
                <p>
                    <iframe scrolling="no" frameborder="0" clocktype="html5" style="overflow:hidden;border:0;margin:0;padding:0;width:450px;height:165px;" src="https://www.clocklink.com/html5embed.php?clock=044&timezone=IST&color=white&size=450&Title=&Message=&Target=&From=2018,1,1,0,0,0&Color=white"></iframe>
                </p>
            </aside>

            <div style="width:60%">
                <p>
                    <div class="fb-share-button"
                         data-href="https://www.facebook.com/CovidApts"
                         data-layout="button_count">
                    </div>
                </p>
                <p>&copy; 2020 - CovidApts</p>
            </div>
        </footer>
    </div>


    <environment include="Development">
        <script src="https://d3js.org/d3.v5.min.js" charset="utf-8"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBIasAC7os8r0Mf0wZnCmj6UTqG51oJX8&callback=initMap">
        </script>

    </environment>
    <environment exclude="Development">
        <script src="https://d3js.org/d3.v5.min.js" charset="utf-8"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDKp42W_7Sc_kcVimZm-pPKG2TCXeFdzto&callback=initMap">
        </script>
    </environment>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(
            $(function () {
                $("#dialog").dialog({
                    autoOpen: false,
                    show: {
                        effect: "blind",
                        duration: 1000
                    }   
                });

                $("#help").click(function () {
                    $("#dialog").dialog("open");
                });
            }));
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>