CovidApts/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CovidApts.Models
{
    public class Apartment
    {
        #region Properties

        public int ApartmentId { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(50)]
        public string Address { get; set; }

        public double Longitude { get; set; }

        public double Latitude { get; set; }

        public string Photo { get; set; }

        [Range(1, 30)]
        [DisplayName("Rooms Number")]
        public int RoomsNumber { get; set; }

        public ICollection<Company> Companies { get; set; }

        #endregion
    }
}

CovidApts/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GoogleMaps.LocationServices;
using GuigleAPI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CovidApts.Data;
using CovidApts.Models;
using System.Net;
using ProtoBuf;
using transit_realtime;
using Geocoding.Microsoft;
using Geocoding;

namespace CovidApts.Controllers
{
    public class ApartmentsController : Controller
    {
        private readonly CovidAptsDbContext _context;
        private readonly IHostingEnvironment he;


        public ApartmentsController(CovidAptsDbContext context, IHostingEnvironment e)
        {
            _context = context;
            he = e;
        }

        // GET: Apartments
        public async Task<IActionResult> Index(String searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(await _context.Apartment.ToListAsync());
            }

            return View(await _context.Apartment.Where(a => a.Address.Contains(searchString)).ToListAsync());
        }

        // GET: Apartments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment.Include(x=> x.Companies)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);

            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apartments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ApartmentId,Address,Photo,RoomsNumber")] Apartment apartment, IFormFile files)
        {
            if (ModelState.IsValid)
            {
                // Getting the long lat
                var location = AddLongLatAsync(apartment.Address);
                apartment.Latitude = location.Result.Latitude;
                apartment.Longitude = location.Result.Longitude;
                SavePhoto(apartment, files);
                _context.Add(apartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        private async Task<MapPoint> AddLongLatAsync(string apartmentAddress)
        {
            MapPoint point;

            // Getting the location of the address
            try
            {
                IGeocoder geocoder = new BingMapsGeocoder("AgnX4fQVaxUmGPZMrIAWH2sVbJ34rY2GR-qjkOWUCJprHGbHX5iMfjlq-xOIYelB");
                IEnumerable <Address> addresses = await geocoder.GeocodeAsync(apartmentAddress);

                point = new MapPoint
                {
                    Latitude = addresses.First().Coordinates.Latitude,
                    Longitude = addresses.First().Coordinates.Longitude
                };


            }
            catch (Exception ex)
            {
                Console.WriteLine("----------------------------------------------");
                Console.WriteLine(ex);
                Console.WriteLine("----------------------------------------------");
                point = new MapPoint
                {
                    Latitude = 32.1637206,
                    Longitude = 34.8647352
                };
            }

            return point;
        }

        private void SavePhoto(Apartment apartment, IFormFile files)
        {
            // Sanity check apartment cant be null
            if (apartment == null)
            {
                return;
            }

            // If there is no defined photo, set the default photo
            if (files == null)
            {
                apartment.Photo = "/images/apartments/default_photo.jpg";
                return;
            }

            var fileName = Path.Combine(he.WebRootPath + "/images/apartments", Path.GetFileName(files.FileName));
            apartment.Photo = "/images/apartments/" + files.FileName;

            // If the file does not exist already creating it
            if (!System.IO.File.Exists(fileName))
            {
                files.CopyTo(new FileStream(fileName, FileMode.Create));
            }
        }

        // GET: Apartments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment.FindAsync(id);
            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ApartmentId,Address,Photo,RoomsNumber")] Apartment apartment, IFormFile files)
        {
            if (id != apartment.ApartmentId)
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    SavePhoto(apartment, files);
                }

                try
                {
                    _context.Update(apartment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApartmentExists(apartment.ApartmentId))
                    {
                        return RedirectToAction("NotFoundPage");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        // GET: Apartments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apartment = await _context.Apartment.FindAsync(id);
            _context.Apartment.Remove(apartment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApartmentExists(int id)
        {
            return _context.Apartment.Any(e => e.ApartmentId == id);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult NotFoundPage()
        {
            return View();
        }
    }
}

CovidApts/Views/Apartments/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>Information about Covid Apts</h3>
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

    <p class="newspaper">
        Covid Apts is an applicatino that came to solve the loneliness of working people at their new workspace - their home. This platform lets people to post their own apartments as a working place and companies will be able to 'rent' them for their own people so they can share a shared workspace.
    </p>

<iframe src="https://www.youtube.com/embed/sHP0UIdZyI4" width="560" height="315" frameborder="0" allowfullscreen></iframe>

<video width="560" height="315" controls>
    <source src="~/videos/CovidApts-video03.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>

CovidApts/Views/Apartments/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<div>
    <aside>
        <canvas id="canvas" width="120" height="120" style="background-color:#333"></canvas>
    </aside>
    <address>
        College Of Management<br />
        Elie Wiesel St 2, Rishon LeTsiyon<br />
        <abbr title="Phone">Phone:</abbr>
        *5025
    </address>


</div>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<script>
    var canvas = document.getElementById("canvas");
    var ctx = canvas.getContext("2d");
    var radius = canvas.height / 2;
    ctx.translate(radius, radius);
    radius = radius * 0.90
    setInterval(drawClock, 1000);

    function drawClock() {
        drawFace(ctx, radius);
        drawNumbers(ctx, radius);
        drawTime(ctx, radius);
    }

    function drawFace(ctx, radius) {
        var grad;
        ctx.beginPath();
        ctx.arc(0, 0, radius, 0, 2 * Math.PI);
        ctx.fillStyle = 'white';
        ctx.fill();
        grad = ctx.createRadialGradient(0, 0, radius * 0.95, 0, 0, radius * 1.05);
        grad.addColorStop(0, '#333');
        grad.addColorStop(0.5, 'white');
        grad.addColorStop(1, '#333');
        ctx.strokeStyle = grad;
        ctx.lineWidth = radius * 0.1;
        ctx.stroke();
        ctx.beginPath();
        ctx.arc(0, 0, radius * 0.1, 0, 2 * Math.PI);
        ctx.fillStyle = '#333';
        ctx.fill();
    }

    function drawNumbers(ctx, radius) {
        var ang;
        var num;
        ctx.font = radius * 0.15 + "px arial";
        ctx.textBaseline = "middle";
        ctx.textAlign = "center";
        for (num = 1; num < 13; num++) {
            ang = num * Math.PI / 6;
            ctx.rotate(ang);
            ctx.translate(0, -radius * 0.85);
            ctx.rotate(-ang);
            ctx.fillText(num.toString(), 0, 0);
            ctx.rotate(ang);
            ctx.translate(0, radius * 0.85);
            ctx.rotate(-ang);
        }
    }

    function drawTime(ctx, radius) {
        var now = new Date();
        var hour = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        //hour
        hour = hour % 12;
        hour = (hour * Math.PI / 6) +
            (minute * Math.PI / (6 * 60)) +
            (second * Math.PI / (360 * 60));
        drawHand(ctx, hour, radius * 0.5, radius * 0.07);
        //minute
        minute = (minute * Math.PI / 30) + (second * Math.PI / (30 * 60));
        drawHand(ctx, minute, radius * 0.8, radius * 0.07);
        // second
        second = (second * Math.PI / 30);
        drawHand(ctx, second, radius * 0.9, radius * 0.02);
    }

    function drawHand(ctx, pos, length, width) {
        ctx.beginPath();
        ctx.lineWidth = width;
        ctx.lineCap = "round";
        ctx.moveTo(0, 0);
        ctx.rotate(pos);
        ctx.lineTo(0, -length);
        ctx.stroke();
        ctx.rotate(-pos);
    }
</script>

CovidApts/Views/Apartments/Create.cshtml
@model CovidApts.Models.Apartment

@{
    ViewData["Title"] = "Create";
}
@section Scripts
    {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link rel="stylesheet" href="~/css/main.css" />
}

<div style="float:right">
    <a class="btn btn-default" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back
    </a>
</div>

<h2>Create Apartment</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomsNumber" class="control-label"></label>
                <input asp-for="RoomsNumber" class="form-control" min="1" max="30"/>
                <span asp-validation-for="RoomsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" name="files" />
            </div>
            <br />
            <div class="form-group">
                <Button type="submit" class="btn btn-success">Create</Button>
            </div>
        </form>
    </div>
</div>

CovidApts/Views/Apartments/Delete.cshtml
@model CovidApts.Models.Apartment

@{
    ViewData["Title"] = "Delete";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(
            $(function () {
                $("#dialog-delete").dialog({
                    autoOpen: false,
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    },
                    buttons: {
                        "Yes": function () {
                            $('#delete-form').submit();
                        },
                        No: function () {
                            $(this).dialog("close");
                        }
                    }
                });

                $('[data-confirm]').click(function (e) {
                    $("#dialog-delete").dialog("open");
                });
            }));
    </script>
}
<div style="float:right">
    <a class="btn btn-default" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back
    </a>
</div>
<h2>Delete Apartment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoomsNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoomsNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd>
            <img class="img-large" src="@Url.Content(Model.Photo)" alt="" style="width:400px;height:200px;"/>
        </dd>
    </dl>

    <form asp-action="Delete" id="delete-form">
        <input type="hidden" asp-for="ApartmentId" />
        <Button type="button" class="btn btn-danger" data-confirm="Are you sure?" value="Yes">
            <i class="fa fa-trash-o fa-lg"></i> Delete
        </Button>
    </form>
    <div id="dialog-delete" title="Delete" class="dialog-message">
        <p>Are you sure?</p>
    </div>
</div>

CovidApts/Views/Apartments/Details.cshtml
@model CovidApts.Models.Apartment

@{
    ViewData["Title"] = "Details";
}

@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

<div style="float:right">
    <a class="btn btn-default" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back
    </a> |
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ApartmentId">
        <i class="fa fa-edit"></i> Edit
    </a> |
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.ApartmentId">
        <i class="fa fa-trash-o fa-lg"></i> Delete
    </a>
</div>
<h2>Apartment Details</h2>


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoomsNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoomsNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd>
            <img class="img-large" src="@Url.Content(Model.Photo)" alt="" style="width:400px;height:200px;"/>
        </dd>
    </dl>
</div>


<div>
    <h3>Apartment's location</h3>
    <div style="width:100%">
        <aside style="width:30%; padding-left:2%">
            <h4>Weather Info for address</h4>
            <ul id="weather">

            </ul>
        </aside>
        <div id="map" style="position:relative;width:67%;height:500px;padding-right:3%">></div>
    </div>
</div>

<input type="hidden" value="@Model.Latitude" id="Latitude" />
<input type="hidden" value="@Model.Longitude" id="Longitude" />

<table class="table">
    <thead>
        <tr>
            <th>
                Status
            </th>
            <th>
                Title
            </th>
            <th>
                Content
            </th>
            <th>
                Resources
            </th>
            <th>
                CreationDate
            </th>
            <th>
                ModifiedDate
            </th>
            <th>
                CurrentApartment
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Companies)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    <img class="img-large" src="@Url.Content(item.Resources)" alt="" style="width:200px;height:200px;"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentApartment.Address)
                </td>
                <td>
                    <br>
                    <a class="btn btn-primary" asp-controller="Companies" asp-action="Edit" asp-route-id="@item.CompanyId">
                        <i class="fa fa-edit"></i>
                    </a>
                    <br>
                    <br>
                    <a class="btn btn-primary" asp-controller="Companies" asp-action="Details" asp-route-id="@item.CompanyId">
                        <i class="fa fa-info"></i>
                    </a>
                    <br>
                    <br>
                    <a class="btn btn-danger" asp-controller="Companies" asp-action="Delete" asp-route-id="@item.CompanyId">
                        <i class="fa fa-trash-o fa-lg"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

CovidApts/Views/Apartments/Edit.cshtml
@model CovidApts.Models.Apartment

@{
    ViewData["Title"] = "Edit";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

    <div style="float:right">
        <a class="btn btn-default" asp-action="Index">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
<h2>Edit Apartment</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ApartmentId" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" autofocus/>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomsNumber" class="control-label"></label>
                <input asp-for="RoomsNumber" class="form-control" min="1" max="30"/>
                <span asp-validation-for="RoomsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control" type="hidden" />
                <img class="img-large" src="@Url.Content(Model.Photo)" alt="" style="width:400px;height:200px;"/>
                <div class="form-group">
                    <input type="file" name="files" />
                </div>
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <Button type="submit" class="btn btn-success">Save</Button>
            </div>
        </form>
    </div>
</div>

CovidApts/Views/Apartments/Index.cshtml
@model IEnumerable<CovidApts.Models.Apartment>

@{
    ViewData["Title"] = "Index";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/search.css" />
}
<form asp-controller="Apartments" asp-action="Index" method="get">
    <div class="search">
        <input name="SearchString" type="text" class="search-query" placeholder="Search" autofocus />
        <button id="searchButton" class="search-button" type="submit">
            <i class="fa fa-search"></i>
        </button>
    </div>
</form>

<div>
    <a class="btn btn-success" asp-action="Create">
        <i class="fa fa-plus fa-2x"></i> Add
    </a>
    <br />
    <br />
    <br />
    <div>
        <section class="tiles">
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <article class="style1">
                        <span class="image">
                            <img class="img-rounded photo-big" src="@Url.Content(item.Photo)" alt="" style="width:400px;height:200px;"/>
                        </span>
                        <a asp-action="Details" asp-route-id="@item.ApartmentId">
                            <h2>@Html.DisplayFor(modelItem => item.Address)</h2>
                            <div class="content">
                                <p>@Html.DisplayFor(modelItem => item.RoomsNumber)</p>
                            </div>
                        </a>

                    </article>
                }
            }
        </section>
    </div>
</div>

CovidApts/Views/Apartments/NotFoundPage.cshtml
@{
    ViewData["Title"] = "NotFound";
}

@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

<h2>This Page Could Not Be Found At This Moment</h2>
<p>This error may occur if you tried to edit a page that already been deleted or entered to an non-existing address</p>